### PR TITLE
tool i made from yours maybe that will interest you

### PR DESCRIPTION
**Pull request by Awajsbro**
=== charm_extraction.py Charm.py ===
I add the frame name at the charm to find it more easily on my chest

=== skillsRank.json ===
All skills with a ranking value base on god talisman checker at https://gamewith.net/monsterhunter-rise/article/show/28392

=== skillsToJewel.json ===
All skills we can craft as jewel with the jewel's lvl

=== trashSkills.txt ===
File for write skills name for ignore it during the ranking process if the user really don't care about some skills

=== rebirth.py ===
Get the charms.json make by your utsushis_charm for ranking all charms and give a liste of charm you can rebirth
Charms for rebirth are charms you can "remake" with another
ex: you can make any charm with 1 skill at 1 lvl with a 3slot charm
Also create a json file for the ranked charms and another for the charm to rebirth
run it with: "python rebirth.py"

=== More ===
I'm not a python dev so sorry if i maybe do some bad stuff
Feel free to integrete the rebirth.py if you want
my apologies for my english and thank you a lot for utsushi_charm you save to me a great amount of time =D

### CODE REVIEW

**Comment by Awajsbro** [comment]
I have get the score by inspect the page of god talisman checker that was in the html so we can do what we want with
If you want to change the score of a skill you just have to modify in data/skillsRank.json

The calculation of the score is the sum of the scores of the slots plus the sum of the scores of the skills multiply by their level
With 500 for lvl1 slot 3500 for lvl2 slot and 4000 for lvl3 slot

I think skill ranking by capcom can just tell if we got the better charm it can be roll but not necessarily the useful one
But I know this ranking method is not very good, I just get it because that the only one I found and I don't think I've enough mh experience for making a good one by myself
And in reality I only check the weak one for rebirth if I need to have a charm for a set that mh-rise.wiki who tell me which ^^

Ok just tell me when you have finish your change and i will try to fix broken part

For the frame_loc that because if i want to find a talisman in my chest it more easily to do with the picture
but a better option for me is to use the page number, the ligne and the column
In all case it may becomes obsolete at the first new roll, rebirth, sell or whatever and i don't have solve for this

sorry i forget to rewrite them ^^'
A google spreadsheets with many skill language 
https://docs.google.com/spreadsheets/d/1ce4_R7HvBPPYE63qyGfeI-nTTSBDsGCGc7ETTGHqYac/edit?usp=sharing

**Comment by chpoit** [comment]
I'm on EST, thanks a lot for the skill list, I was able to add support for multiple languages with that. Seriously tho, why are all the french names so goofy... Je suis le pourfendeur de dragons, l'acrobate spartiate avec le savoir faire d'un samourai :P

I'll look into wether or not gamewith allow for the sharing of their data under MIT license. 
However, I've been thinking that it might be better to just ship a few presets people can pick and use to favor certain skills and trash others.

**Comment by Awajsbro** [comment]
you're welcome I do it really quick thank to a website I've found.
Yes i agree with you but in practice the french name don't tell what the skill does so I find playing in english is more practical.

I'm a bit naive and i think all that is in clear on internet are free, but that true gamewith may not have the vision.

like some set for full attack with AB WEX etc, elem attack with all elemBosst or for tanking with defense and regen
If that's what you suggest i think this is a good idea specially if we can pick more than one set at the same time.

**Comment by chpoit** [comment]
I've decided to merge this in a side branch and start implementing rebirth with skill groups/presets that are independant to avoid using gamewith's data.

**Pull request merged**
